### ISSUE TITLE
Internal server error when calling schemaView - Python3.6 regex issue

### ISSUE THREAD

**Issue by arvindnrbt** [axnsan12/drf-yasg#193]
**Traceback:**
```
Log file created on 2018-08-29T14:59:17.623254
29-08-2018:14:59:21,302 ERROR    [exception.py:118] Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/drf_yasg/views.py", line 31, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/views/decorators/vary.py", line 20, in inner_func
    response = func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/drf_yasg/views.py", line 84, in get
    schema = generator.get_schema(request, self.public)
  File "/usr/lib/python3.6/site-packages/drf_yasg/generators.py", line 217, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
  File "/usr/lib/python3.6/site-packages/drf_yasg/generators.py", line 339, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
  File "/usr/lib/python3.6/site-packages/drf_yasg/generators.py", line 381, in get_operation
    operation = view_inspector.get_operation(operation_keys)
  File "/usr/lib/python3.6/site-packages/drf_yasg/inspectors/view.py", line 41, in get_operation
    responses = self.get_responses()
  File "/usr/lib/python3.6/site-packages/drf_yasg/inspectors/view.py", line 170, in get_responses
    response_serializers = self.get_response_serializers()
  File "/usr/lib/python3.6/site-packages/drf_yasg/inspectors/view.py", line 215, in get_response_serializers
    responses = self.get_default_responses()
  File "/usr/lib/python3.6/site-packages/drf_yasg/inspectors/view.py", line 191, in get_default_responses
    default_schema = self.serializer_to_schema(default_schema) or ''
  File "/usr/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 377, in serializer_to_schema
    self.field_inspectors, 'get_schema', serializer, {'field_inspectors': self.field_inspectors}
  File "/usr/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 73, in probe_inspectors
    result = method(obj, **kwargs)
  File "/usr/lib/python3.6/site-packages/drf_yasg/inspectors/field.py", line 39, in get_schema
    return self.probe_field_inspectors(serializer, openapi.Schema, self.use_definitions)
  File "/usr/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 164, in probe_field_inspectors
    swagger_object_type=swagger_object_type, use_references=use_references, **kwargs
  File "/usr/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 73, in probe_inspectors
    result = method(obj, **kwargs)
  File "/usr/lib/python3.6/site-packages/drf_yasg/inspectors/field.py", line 127, in field_to_swagger_object
    definitions.setdefault(ref_name, make_schema_definition)
  File "/usr/lib/python3.6/site-packages/drf_yasg/openapi.py", line 630, in setdefault
    ret = maker()
  File "/usr/lib/python3.6/site-packages/drf_yasg/inspectors/field.py", line 100, in make_schema_definition
    child, ChildSwaggerType, use_references, **prop_kwargs
  File "/usr/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 164, in probe_field_inspectors
    swagger_object_type=swagger_object_type, use_references=use_references, **kwargs
  File "/usr/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 73, in probe_inspectors
    result = method(obj, **kwargs)
  File "/usr/lib/python3.6/site-packages/drf_yasg/inspectors/field.py", line 418, in field_to_swagger_object
    type_info = get_basic_type_info(field)
  File "/usr/lib/python3.6/site-packages/drf_yasg/inspectors/field.py", line 398, in get_basic_type_info
    pattern = find_regex(field)
  File "/usr/lib/python3.6/site-packages/drf_yasg/inspectors/field.py", line 263, in find_regex
    pattern = getattr(getattr(regex_validator, 'regex', None), 'pattern', None)
  File "/usr/lib/python3.6/site-packages/django/utils/functional.py", line 215, in inner
    self._setup()
  File "/usr/lib/python3.6/site-packages/django/utils/functional.py", line 349, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/lib/python3.6/site-packages/django/core/validators.py", line 21, in _compile
    return re.compile(regex, flags)
  File "/usr/lib/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.6/sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/usr/lib/python3.6/sre_parse.py", line 553, in _parse
    raise source.error(msg, len(this) + 1 + len(that))
sre_constants.error: bad character range _-  at position 11
```
This issue is cropping out of nowhere. Any idea why it happens?

**Comment by axnsan12** [comment]
This happens because you have an invalid regex validator somewhere on your models/serializers.

RegexValidator stores its [regex in a lazy object](https://github.com/django/django/blob/22e8ab02863819093832de9f771bf40a62a6bd4a/django/core/validators.py#L16), and [this line](https://github.com/axnsan12/drf-yasg/blob/9b56e1a4c839906d92e0568904731855bdce51a1/src/drf_yasg/inspectors/field.py#L264) triggers the compilation of the faulty regex.

The error diagnostic could be better...
