### ISSUE TITLE
request_body throwing error even thought its assigned to a valid Serializer

### ISSUE THREAD

**Issue by gitstercode** [axnsan12/drf-yasg#280]
Error:
drf_yasg.errors.SwaggerGenerationError: specify the body parameter as a Schema or Serializer in request_body`

Can someone help if I am missing something here ?
I am trying to generate swagger.json

#### Trial1:
```python
@swagger_auto_schema(
        operation_description="apiview post description override",
        request_body=openapi.Schema(
            type=openapi.TYPE_OBJECT,
            required=['username'],
            properties={
                'username': openapi.Schema(type=openapi.TYPE_STRING)
            },
        ),
        security=[]
    )
```

#### Trial2:
```python
   @swagger_auto_schema(
        operation_description="apiview post description override",
        request_body=SampleSerializer
    )
```

#### Valid Serializer:
```python
class SampleSerializer(serializers.Serializer):
    username=serializers.IntegerField()
```

#### Error Log:
```
(.devices_venv) devicesapi $python manage.py generate_swagger -o docs/ub-swagger.json -u http://localhost.apple.com:8302
Traceback (most recent call last):
  File "manage.py", line 37, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/varun/.devices_venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/varun/.devices_venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/varun/.devices_venv/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/varun/.devices_venv/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/varun/.devices_venv/lib/python2.7/site-packages/drf_yasg/management/commands/generate_swagger.py", line 154, in handle
    schema = generator.get_schema(request=request, public=not private)
  File "/Users/varun/.devices_venv/lib/python2.7/site-packages/drf_yasg/generators.py", line 216, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
  File "/Users/varun/.devices_venv/lib/python2.7/site-packages/drf_yasg/generators.py", line 338, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
  File "/Users/varun/.devices_venv/lib/python2.7/site-packages/drf_yasg/generators.py", line 380, in get_operation
    operation = view_inspector.get_operation(operation_keys)
  File "/Users/varun/.devices_venv/lib/python2.7/site-packages/drf_yasg/inspectors/view.py", line 33, in get_operation
    parameters = self.add_manual_parameters(parameters)
  File "/Users/varun/.devices_venv/lib/python2.7/site-packages/drf_yasg/inspectors/view.py", line 162, in add_manual_parameters
    raise SwaggerGenerationError("specify the body parameter as a Schema or Serializer in request_body")
drf_yasg.errors.SwaggerGenerationError: specify the body parameter as a Schema or Serializer in request_body
```

**Comment by axnsan12** [comment]
This is almost certainly caused by other code, specifically a manual_parameters array containing an openapi.Schema with IN_BODY.

**Comment by brianou7** [comment]
So, like @axnsan12 said, this error is associated with a combination of `manual_parameters` and `swagger_auto_schema`... 

The answer to this question on Stackoverflow was a great help to me: [drf-yasg swagger setup parameters IN_BODY is not worked](https://stackoverflow.com/questions/62930918/drf-yasg-swagger-setup-parameters-in-body-is-not-worked)
