### ISSUE TITLE
patterns not working with django > 2

### ISSUE THREAD

**Issue by marco-silva0000** [axnsan12/drf-yasg#374]
Either I'm doing something wrong, or the patterns don't work with the [new path url](https://docs.djangoproject.com/en/2.2/ref/urls/#path) declaration of the newer django versions

```
schema_view = get_schema_view(
    openapi.Info(
        title="Reusable app API", default_version="v1", description="description placeholder"
    ),
    public=True, 
    patterns=['reusableappname'],
)
```

I've also tried with regex strings r'reusableappname' but I have the same error, wich is:
`AttributeError: 'str' object has no attribute 'regex'`

this is raised in [get_original_route](https://github.com/encode/django-rest-framework/blob/10a0b42b749bd5965ea925633ff5b36e3b53bf74/rest_framework/compat.py#L29) of drf

I believe that this project ir removing some property, as the process should go to the different if branch.

Full traceback:

```
Internal Server Error: /apps/cantoes/api/
Traceback (most recent call last):
  File "/home/msilva/.local/share/virtualenvs/regantes-backend-VEQEWK_9/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/msilva/.local/share/virtualenvs/regantes-backend-VEQEWK_9/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/msilva/.local/share/virtualenvs/regantes-backend-VEQEWK_9/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/msilva/.local/share/virtualenvs/regantes-backend-VEQEWK_9/lib/python3.7/site-packages/drf_yasg/views.py", line 35, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/msilva/.local/share/virtualenvs/regantes-backend-VEQEWK_9/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/msilva/.local/share/virtualenvs/regantes-backend-VEQEWK_9/lib/python3.7/site-packages/django/views/decorators/vary.py", line 20, in inner_func
    response = func(*args, **kwargs)
  File "/home/msilva/.local/share/virtualenvs/regantes-backend-VEQEWK_9/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/msilva/.local/share/virtualenvs/regantes-backend-VEQEWK_9/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/msilva/.local/share/virtualenvs/regantes-backend-VEQEWK_9/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/msilva/.local/share/virtualenvs/regantes-backend-VEQEWK_9/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/msilva/.local/share/virtualenvs/regantes-backend-VEQEWK_9/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/msilva/.local/share/virtualenvs/regantes-backend-VEQEWK_9/lib/python3.7/site-packages/drf_yasg/views.py", line 95, in get
    schema = generator.get_schema(request, self.public)
  File "/home/msilva/.local/share/virtualenvs/regantes-backend-VEQEWK_9/lib/python3.7/site-packages/drf_yasg/generators.py", line 240, in get_schema
    endpoints = self.get_endpoints(request)
  File "/home/msilva/.local/share/virtualenvs/regantes-backend-VEQEWK_9/lib/python3.7/site-packages/drf_yasg/generators.py", line 310, in get_endpoints
    endpoints = enumerator.get_api_endpoints()
  File "/home/msilva/.local/share/virtualenvs/regantes-backend-VEQEWK_9/lib/python3.7/site-packages/drf_yasg/generators.py", line 87, in get_api_endpoints
    path_regex = prefix + get_original_route(pattern)
  File "/home/msilva/.local/share/virtualenvs/regantes-backend-VEQEWK_9/lib/python3.7/site-packages/rest_framework/compat.py", line 56, in get_original_route
    return urlpattern.regex.pattern
AttributeError: 'str' object has no attribute 'regex'
```

```
# cantoes/urls.py, this is a reusable app
schema_view = get_schema_view(
    openapi.Info(
        title="Cantoes API", default_version="v1", description="Test description"
    ),
    public=True,
    patterns=[r"cantoes"],
)

router = DefaultRouter()
router.register(r"corner-man", api.CornerManViewSet)
router.register(r"corner", api.CornerViewSet)

# adds a required property to be used as base view of DRF router
class myView: #  some magic that is probably a bad hack but idk how to fix it
    @classmethod
    def as_view(*args, **kwargs):
        return schema_view.with_ui("swagger", cache_timeout=None)


router.APIRootView = myView

urlpatterns = [path("api/", include(router.urls))]
```

```
# project/urls.py base project that imports the reusable app
urlpatterns = [
    path("admin/", admin.site.urls),
    path("apps/cantoes/", include("cantoes.urls")),
    path("some-other-app/", include("some_other_app.urls")),
    path("cantoes/", include("cantoes.urls")),
]
```

**Comment by kidig** [comment]
My solution for django 2 is:

```python
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

SchemaView = get_schema_view(
    openapi.Info(
        title="Project API",
        default_version='v1',
    ),
    public=False,
    permission_classes=(permissions.AllowAny,)
)

urlpatterns = [
    re_path("^swagger(?P<format>.json|.yaml)$", SchemaView.without_ui(cache_timeout=0), name='schema-json'),
    path("swagger/", SchemaView.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path("redoc/", SchemaView.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

```

**Comment by axnsan12** [comment]
`patterns` must be a list of urlpatterns, not a module name. Try setting `urlconf` to `cantoes.urls`.
