### ISSUE TITLE
serializer exception when run sample code in online instruction

### ISSUE THREAD

**Issue by huifeidepangzi** [axnsan12/drf-yasg#379]
Hi there,
When I run code 
```
schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)
```

it always give me a error: 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/drf_yasg/views.py", line 95, in get
    schema = generator.get_schema(request, self.public)
  File "/usr/local/lib/python3.6/site-packages/drf_yasg/generators.py", line 244, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
  File "/usr/local/lib/python3.6/site-packages/drf_yasg/generators.py", line 402, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
  File "/usr/local/lib/python3.6/site-packages/drf_yasg/generators.py", line 444, in get_operation
    operation = view_inspector.get_operation(operation_keys)
  File "/usr/local/lib/python3.6/site-packages/drf_yasg/inspectors/view.py", line 42, in get_operation
    responses = self.get_responses()
  File "/usr/local/lib/python3.6/site-packages/drf_yasg/inspectors/view.py", line 177, in get_responses
    response_serializers = self.get_response_serializers()
  File "/usr/local/lib/python3.6/site-packages/drf_yasg/inspectors/view.py", line 232, in get_response_serializers
    responses = self.get_default_responses()
  File "/usr/local/lib/python3.6/site-packages/drf_yasg/inspectors/view.py", line 208, in get_default_responses
    default_schema = self.serializer_to_schema(default_schema) or ''
  File "/usr/local/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 446, in serializer_to_schema
    self.field_inspectors, 'get_schema', serializer, {'field_inspectors': self.field_inspectors}
  File "/usr/local/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 118, in probe_inspectors
    result = method(obj, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/drf_yasg/inspectors/field.py", line 41, in get_schema
    return self.probe_field_inspectors(serializer, openapi.Schema, self.use_definitions)
  File "/usr/local/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 238, in probe_field_inspectors
    swagger_object_type=swagger_object_type, use_references=use_references, **kwargs
  File "/usr/local/lib/python3.6/site-packages/drf_yasg/inspectors/base.py", line 118, in probe_inspectors
    result = method(obj, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/drf_yasg/inspectors/field.py", line 134, in field_to_swagger_object
    actual_schema = definitions.setdefault(ref_name, make_schema_definition)
  File "/usr/local/lib/python3.6/site-packages/drf_yasg/openapi.py", line 690, in setdefault
    ret = maker()
  File "/usr/local/lib/python3.6/site-packages/drf_yasg/inspectors/field.py", line 101, in make_schema_definition
    for property_name, child in serializer.fields.items():
  File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py", line 363, in fields
    for key, value in self.get_fields().items():
  File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py", line 1025, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py", line 1102, in get_field_names
    serializer_class=self.__class__.__name__
**AssertionError: ("Creating a ModelSerializer without either the 'fields' attribute or the 'exclude' attribute has been deprecated since 3.3.0, and is now disallowed. Add an explicit fields = '__all__' to the MutedIntegrationSerializer serializer.",)**
ERROR  2019-06-10 22:10:52,872   django.server:log_message
```

Do I miss something here? but the code I run is come from https://drf-yasg.readthedocs.io/en/1.15.0/readme.html which should be correct

btw the version of libraries I use are:
django-rest-framework: 3.9.4
django core: 1.11.21
drf-yasg: 1.15.0

**Comment by axnsan12** [comment]
This is because your `MutedIntegrationSerializer` is incorrect - it must have either `fields` or `exclude` on its `Meta`, as the error says.
