### ISSUE TITLE
AttributeError: type object 'unicode' has no attribute '__args__'

### ISSUE THREAD

**Issue by nedbat** [axnsan12/drf-yasg#381]
Using drf-yasg 1.15.0 with django-rest-framework 3.7.7, I am seeing this error when trying to generate openapi docs.

The problem seems to stem from [this choices field](https://github.com/edx/edx-platform/blob/4d68c8fbdf335ea58f840dc48016d4ca81ee7c2d/cms/djangoapps/api/v1/serializers/course_runs.py#L127-L128):
```
class CourseRunSerializerCommonFieldsMixin(serializers.Serializer):
    schedule = CourseRunScheduleSerializer(source='*', required=False)
    pacing_type = CourseRunPacingTypeField(source='self_paced', required=False,
                                           choices=((False, 'instructor_paced'), (True, 'self_paced'),))
```
If I comment out the `pacing_type` field in this class, the openapi docs generate successfully.

Debugging through the code, `field_to_swagger_object` is seeing that both choices are unicode strings, and since unicode is a subclass of typing.Sequence, calls `inspect_collection_hint_class(unicode)`.  But unicode doesn't have an `__args__` attribute.

I'm not sure what's wrong here.  Perhaps we've constructed the serializers incorrectly?  

The full traceback is:
```
2019-06-12 21:20:35,624 ERROR 6291 [django.request] [user None] exception.py:135 - Internal Server Error: /swagger/
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/rest_framework/views.py", line 494, in dispatch
    response = self.handle_exception(exc)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/rest_framework/views.py", line 454, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/rest_framework/views.py", line 491, in dispatch
    response = handler(request, *args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/drf_yasg/views.py", line 95, in get
    schema = generator.get_schema(request, self.public)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/drf_yasg/generators.py", line 244, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/drf_yasg/generators.py", line 402, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/drf_yasg/generators.py", line 444, in get_operation
    operation = view_inspector.get_operation(operation_keys)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/drf_yasg/inspectors/view.py", line 42, in get_operation
    responses = self.get_responses()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/drf_yasg/inspectors/view.py", line 177, in get_responses
    response_serializers = self.get_response_serializers()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/drf_yasg/inspectors/view.py", line 232, in get_response_serializers
    responses = self.get_default_responses()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/drf_yasg/inspectors/view.py", line 208, in get_default_responses
    default_schema = self.serializer_to_schema(default_schema) or ''
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/drf_yasg/inspectors/base.py", line 446, in serializer_to_schema
    self.field_inspectors, 'get_schema', serializer, {'field_inspectors': self.field_inspectors}
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/drf_yasg/inspectors/base.py", line 118, in probe_inspectors
    result = method(obj, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/drf_yasg/inspectors/field.py", line 41, in get_schema
    return self.probe_field_inspectors(serializer, openapi.Schema, self.use_definitions)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/drf_yasg/inspectors/base.py", line 238, in probe_field_inspectors
    swagger_object_type=swagger_object_type, use_references=use_references, **kwargs
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/drf_yasg/inspectors/base.py", line 118, in probe_inspectors
    result = method(obj, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/drf_yasg/inspectors/field.py", line 134, in field_to_swagger_object
    actual_schema = definitions.setdefault(ref_name, make_schema_definition)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/drf_yasg/openapi.py", line 690, in setdefault
    ret = maker()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/drf_yasg/inspectors/field.py", line 109, in make_schema_definition
    child, ChildSwaggerType, use_references, **prop_kwargs
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/drf_yasg/inspectors/base.py", line 238, in probe_field_inspectors
    swagger_object_type=swagger_object_type, use_references=use_references, **kwargs
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/drf_yasg/inspectors/base.py", line 118, in probe_inspectors
    result = method(obj, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/drf_yasg/inspectors/field.py", line 662, in field_to_swagger_object
    values_type = get_basic_type_info_from_hint(next(iter(enum_value_types)))
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/drf_yasg/inspectors/field.py", line 542, in get_basic_type_info_from_hint
    return info(hint_class)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/drf_yasg/inspectors/field.py", line 494, in inspect_collection_hint_class
    args = hint_class.__args__
AttributeError: type object 'unicode' has no attribute '__args__'
```

**Comment by nedbat** [comment]
Oops, now I see that pull request #363 fixes this.  Can we get it merged? Is there something I can do to help?

**Comment by axnsan12** [comment]
The PR is merged now. Please close the issue once you confirm that it's fixed for you.

**Comment by nedbat** [comment]
Yes, thanks. Commit b5aba7243dad8a5296e3ab11a3dff45bf1972e4a fixes the problem for me.  Will there be a new release?
