### ISSUE TITLE
ImproperlyConfigured: Returned a template response with no `template_name` attribute set on either the view or response

### ISSUE THREAD

**Issue by fuckthegoose** [axnsan12/drf-yasg#532]
I installed everything as it is written in the documentation, when I contact the route to which I find swagger I get an exception

```
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_yasg'
]
```

urls.py
```
schema_view = get_schema_view(
   openapi.Info(
      title="API",
      default_version='v1',
      description="Test description",
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('timetracker/', include('apps.timetracker.urls')),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/usr/local/lib/python3.8/site-packages/drf_yasg/renderers.py", line 72, in render
    return TemplateHTMLRenderer().render(swagger, accepted_media_type, renderer_context)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/renderers.py", line 159, in render
    template_names = self.get_template_names(response, view)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/renderers.py", line 187, in get_template_names
    raise ImproperlyConfigured(

Exception Type: ImproperlyConfigured at /swagger/
Exception Value: Returned a template response with no `template_name` attribute set on either the view or response
```

**Comment by FendyPierre** [comment]
@fuckthegoose did you resolve this? I'm getting the same.

**Comment by girlProg** [comment]
add format you're interested in eg
`{{server}}/api/getbatch?format=json`

**Comment by frontendr** [comment]
I got this error with clients that send an `OPTIONS` request. I've fixed like this:

```
schema_view = get_schema_view(...)
schema_view.http_method_names = ["get"]
# then add it to urls...
```
