### ISSUE TITLE
add support for primitive `list`

### ISSUE THREAD

**Issue by tomwojcik** [axnsan12/drf-yasg#627]
I tried to add `drf-yasg` to a rather complicated project with a lot of typing but it breaks on list.

I think the problem lies somewhere around here
https://github.com/axnsan12/drf-yasg/blob/9ccf24c27ad46db4f566170553d49d687b6d21d6/src/drf_yasg/inspectors/field.py#L481-L508

I'm not sure how exactly it is handled here but I don't think `list` should ever reach `inspect_collection_hint_class`.

Is there a reason for not having `(list, (openapi.ARRAY_FIELD, None))` in `hinting_type_info` ? 
Is it because of `typing.Sequence` that's being added? But `typing.List` has `__args__` and `list` doesn't.

Here it lacks of test case for `list`
https://github.com/axnsan12/drf-yasg/blob/9ccf24c27ad46db4f566170553d49d687b6d21d6/tests/test_get_basic_type_info_from_hint.py#L15-L40

Happy to open a PR with test and fix.

MacOS
Py 3.8
Django 3.1
DRF 3.11.1

Stacktrace

```
fs_django  | [INFO/fs:82] GET /swagger/?format=openapi REQUEST
fs_django  | [ERROR/root:15] Bad request
fs_django  | Traceback (most recent call last):
fs_django  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
fs_django  |     response = handler(request, *args, **kwargs)
fs_django  |   File "/usr/local/lib/python3.8/site-packages/drf_yasg/views.py", line 94, in get
fs_django  |     schema = generator.get_schema(request, self.public)
fs_django  |   File "/usr/local/lib/python3.8/site-packages/drf_yasg/generators.py", line 254, in get_schema
fs_django  |     paths, prefix = self.get_paths(endpoints, components, request, public)
fs_django  |   File "/usr/local/lib/python3.8/site-packages/drf_yasg/generators.py", line 412, in get_paths
fs_django  |     operation = self.get_operation(view, path, prefix, method, components, request)
fs_django  |   File "/usr/local/lib/python3.8/site-packages/drf_yasg/generators.py", line 454, in get_operation
fs_django  |     operation = view_inspector.get_operation(operation_keys)
fs_django  |   File "/usr/local/lib/python3.8/site-packages/drf_yasg/inspectors/view.py", line 45, in get_operation
fs_django  |     responses = self.get_responses()
fs_django  |   File "/usr/local/lib/python3.8/site-packages/drf_yasg/inspectors/view.py", line 180, in get_responses
fs_django  |     response_serializers = self.get_response_serializers()
fs_django  |   File "/usr/local/lib/python3.8/site-packages/drf_yasg/inspectors/view.py", line 235, in get_response_serializers
fs_django  |     responses = self.get_default_responses()
fs_django  |   File "/usr/local/lib/python3.8/site-packages/drf_yasg/inspectors/view.py", line 211, in get_default_responses
fs_django  |     default_schema = self.serializer_to_schema(default_schema) or ''
fs_django  |   File "/usr/local/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 445, in serializer_to_schema
fs_django  |     return self.probe_inspectors(
fs_django  |   File "/usr/local/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 118, in probe_inspectors
fs_django  |     result = method(obj, **kwargs)
fs_django  |   File "/usr/local/lib/python3.8/site-packages/drf_yasg/inspectors/field.py", line 42, in get_schema
fs_django  |     return self.probe_field_inspectors(serializer, openapi.Schema, self.use_definitions)
fs_django  |   File "/usr/local/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 236, in probe_field_inspectors
fs_django  |     return self.probe_inspectors(
fs_django  |   File "/usr/local/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 118, in probe_inspectors
fs_django  |     result = method(obj, **kwargs)
fs_django  |   File "/usr/local/lib/python3.8/site-packages/drf_yasg/inspectors/field.py", line 135, in field_to_swagger_object
fs_django  |     actual_schema = definitions.setdefault(ref_name, make_schema_definition)
fs_django  |   File "/usr/local/lib/python3.8/site-packages/drf_yasg/openapi.py", line 690, in setdefault
fs_django  |     ret = maker()
fs_django  |   File "/usr/local/lib/python3.8/site-packages/drf_yasg/inspectors/field.py", line 109, in make_schema_definition
fs_django  |     child_schema = self.probe_field_inspectors(
fs_django  |   File "/usr/local/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 236, in probe_field_inspectors
fs_django  |     return self.probe_inspectors(
fs_django  |   File "/usr/local/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 118, in probe_inspectors
fs_django  |     result = method(obj, **kwargs)
fs_django  |   File "/usr/local/lib/python3.8/site-packages/drf_yasg/inspectors/field.py", line 86, in field_to_swagger_object
fs_django  |     child_schema = self.probe_field_inspectors(field.child, ChildSwaggerType, use_references)
fs_django  |   File "/usr/local/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 236, in probe_field_inspectors
fs_django  |     return self.probe_inspectors(
fs_django  |   File "/usr/local/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 118, in probe_inspectors
fs_django  |     result = method(obj, **kwargs)
fs_django  |   File "/usr/local/lib/python3.8/site-packages/drf_yasg/inspectors/field.py", line 135, in field_to_swagger_object
fs_django  |     actual_schema = definitions.setdefault(ref_name, make_schema_definition)
fs_django  |   File "/usr/local/lib/python3.8/site-packages/drf_yasg/openapi.py", line 690, in setdefault
fs_django  |     ret = maker()
fs_django  |   File "/usr/local/lib/python3.8/site-packages/drf_yasg/inspectors/field.py", line 109, in make_schema_definition
fs_django  |     child_schema = self.probe_field_inspectors(
fs_django  |   File "/usr/local/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 236, in probe_field_inspectors
fs_django  |     return self.probe_inspectors(
fs_django  |   File "/usr/local/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 118, in probe_inspectors
fs_django  |     result = method(obj, **kwargs)
fs_django  |   File "/usr/local/lib/python3.8/site-packages/drf_yasg/inspectors/field.py", line 616, in field_to_swagger_object
fs_django  |     type_info = get_basic_type_info_from_hint(hint_class)
fs_django  |   File "/usr/local/lib/python3.8/site-packages/drf_yasg/inspectors/field.py", line 550, in get_basic_type_info_from_hint
fs_django  |     return info(hint_class)
fs_django  |   File "/usr/local/lib/python3.8/site-packages/drf_yasg/inspectors/field.py", line 499, in inspect_collection_hint_class
fs_django  |     args = hint_class.__args__
fs_django  | AttributeError: type object 'list' has no attribute '__args__'
```

**Comment by tomwojcik** [comment]
I confirm that changing return type `list` to `List` from `typing` solved the issue. So it's a bug.
