### ISSUE TITLE
Incompatibility with semantic-version library

### ISSUE THREAD

**Issue by aleksandr-hilko** [axnsan12/drf-yasg#639]
Hello. I have a project with such dependencies: python==3.6, django==3.0.10 , django-rest-framework==3.11.1, drf-yasg==1.17.1 , semantic-version==2.8.5.
I've set up schema and url is such a way:

```
def get_swagger_view(title=None, patterns=None, urlconf=None):
    """
    Returns schema view which renders Swagger/OpenAPI.
    """
    schema_view = get_schema_view(
        openapi.Info(
            title=title,
            default_version='1.4.4',
            description="Test description",
            terms_of_service="https://www.google.com/policies/terms/",
            contact=openapi.Contact(email="contact@snippets.local"),
            license=openapi.License(name="BSD License"),
        ),
        public=True,
        patterns=patterns,
        urlconf=urlconf,
        permission_classes=(permissions.AllowAny,),
    )
    return schema_view

api_patterns = [
    ...list of project patterns
]

swagger_schema = get_swagger_view(title='Carson API', patterns=api_patterns)
api_patterns = [path('/api/v1.4.4/swagger/', swagger_schema.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'), *api_patterns]
```
unfortunately when open swagger url I got an AttributeError when SwaggerDict object is trying to recursively convert into an ``OrderedDict`` instance (as_odict method).

 Issue seems to be related with converting semantic_version.base.Version object, because version_string that is passed into Version __init__ is actually a generator, but not a string

Below is a stake trace on an error:

```
backend   | Traceback (most recent call last):
backend   |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
backend   |     response = get_response(request)
backend   |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 145, in _get_response
backend   |     response = self.process_exception_by_middleware(e, request)
backend   |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 143, in _get_response
backend   |     response = response.render()
backend   |   File "/usr/local/lib/python3.6/site-packages/django/template/response.py", line 105, in render
backend   |     self.content = self.rendered_content
backend   |   File "/usr/local/lib/python3.6/site-packages/rest_framework/response.py", line 70, in rendered_content
backend   |     ret = renderer.render(self.data, accepted_media_type, context)
backend   |   File "/usr/local/lib/python3.6/site-packages/drf_yasg/renderers.py", line 37, in render
backend   |     return codec.encode(data)
backend   |   File "/usr/local/lib/python3.6/site-packages/drf_yasg/codecs.py", line 69, in encode
backend   |     spec = self.generate_swagger_object(document)
backend   |   File "/usr/local/lib/python3.6/site-packages/drf_yasg/codecs.py", line 106, in generate_swagger_object
backend   |     return swagger.as_odict()
backend   |   File "/usr/local/lib/python3.6/site-packages/drf_yasg/openapi.py", line 165, in as_odict
backend   |     return SwaggerDict._as_odict(self, {})
backend   |   File "/usr/local/lib/python3.6/site-packages/drf_yasg/openapi.py", line 151, in _as_odict
backend   |     result[attr] = SwaggerDict._as_odict(val, memo)
backend   |   File "/usr/local/lib/python3.6/site-packages/drf_yasg/openapi.py", line 151, in _as_odict
backend   |     result[attr] = SwaggerDict._as_odict(val, memo)
backend   |   File "/usr/local/lib/python3.6/site-packages/drf_yasg/openapi.py", line 156, in _as_odict
backend   |     return type(obj)(SwaggerDict._as_odict(elem, memo) for elem in obj)
backend   |   File "/usr/local/lib/python3.6/site-packages/semantic_version/base.py", line 105, in __init__
backend   |     major, minor, patch, prerelease, build = self.parse(version_string, partial)
backend   |   File "/usr/local/lib/python3.6/site-packages/semantic_version/base.py", line 309, in parse
backend   |     match = version_re.match(version_string)
backend   | TypeError: expected string or bytes-like object
```
I guess that the issue is in this line:

` type(obj)(SwaggerDict._as_odict(elem, memo) for elem in obj) `

where obj is an instance of Version class.

**Comment by aleksandr-hilko** [comment]
Closing it, as it was related with our CustomNamespaceVersioning class that returned Version objects rather than string.
