### ISSUE TITLE
coreschema does not get installed with 1.21.6

### ISSUE THREAD

**Issue by skamansam** [axnsan12/drf-yasg#861]
# Bug Report

## Description

After upgrading drf-yasg to 1.21.6, schema generation fails.

## Is this a regression?

Yes, the previous version in which this bug was not present was: 1.21.4

Downgrading installs the necessary requirements:

```
> poetry add drf-yasg==1.21.4
Skipping virtualenv creation, as specified in config file.

Updating dependencies
Resolving dependencies... (396.8s)

Package operations: 3 installs, 1 update, 0 removals

  • Installing coreschema (0.0.4)
  • Installing itypes (1.2.0)
  • Installing coreapi (2.3.3)
  • Updating drf-yasg (1.21.6 -> 1.21.4)

Writing lock file
```

## Minimal Reproduction
Start a new django project with the following packages installed:
```code
Django == 4.2.3
django-filter == 23.2
djangorestframework == 3.14.0
drf-yasg == 1.21.6
```
Test module availability:

```
> python -m coreschema --version
/home/sam/.cache/pypoetry/virtualenvs/django-drf-yasg-test-GpqI3KCz-py3.11/bin/python: No module named coreschema
```

## Stack trace / Error message

```code
  File "/home/sam/.pyenv/versions/3.11.2/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/.pyenv/versions/3.11.2/lib/python3.11/site-packages/drf_yasg/views.py", line 94, in get
    schema = generator.get_schema(request, self.public)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/.pyenv/versions/3.11.2/lib/python3.11/site-packages/drf_yasg/generators.py", line 276, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/.pyenv/versions/3.11.2/lib/python3.11/site-packages/drf_yasg/generators.py", line 482, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/.pyenv/versions/3.11.2/lib/python3.11/site-packages/drf_yasg/generators.py", line 524, in get_operation
    operation = view_inspector.get_operation(operation_keys)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/.pyenv/versions/3.11.2/lib/python3.11/site-packages/drf_yasg/inspectors/view.py", line 33, in get_operation
    query = self.get_query_parameters()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/.pyenv/versions/3.11.2/lib/python3.11/site-packages/drf_yasg/inspectors/view.py", line 293, in get_query_parameters
    natural_parameters = self.get_filter_parameters() + self.get_pagination_parameters()
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/.pyenv/versions/3.11.2/lib/python3.11/site-packages/drf_yasg/inspectors/base.py", line 428, in get_pagination_parameters
    return self.probe_inspectors(self.paginator_inspectors, 'get_paginator_parameters',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/.pyenv/versions/3.11.2/lib/python3.11/site-packages/drf_yasg/inspectors/base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/.pyenv/versions/3.11.2/lib/python3.11/site-packages/drf_yasg/inspectors/query.py", line 22, in get_paginator_parameters
    fields = paginator.get_schema_fields(self.view)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/.pyenv/versions/3.11.2/lib/python3.11/site-packages/rest_framework/pagination.py", line 313, in get_schema_fields
    assert coreapi is not None, 'coreapi must be installed to use `get_schema_fields()`'
           ^^^^^^^^^^^^^^^^^^^
AssertionError: coreapi must be installed to use `get_schema_fields()`

Traceback (most recent call last):
  File "/home/sam/.pyenv/versions/3.11.2/lib/python3.11/site-packages/django/contrib/staticfiles/handlers.py", line 80, in __call__
    return self.application(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/.pyenv/versions/3.11.2/lib/python3.11/site-packages/django/core/handlers/wsgi.py", line 124, in __call__
    response = self.get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/.pyenv/versions/3.11.2/lib/python3.11/site-packages/django/core/handlers/base.py", line 140, in get_response
    response = self._middleware_chain(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/.pyenv/versions/3.11.2/lib/python3.11/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/.pyenv/versions/3.11.2/lib/python3.11/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/.pyenv/versions/3.11.2/lib/python3.11/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/.pyenv/versions/3.11.2/lib/python3.11/site-packages/django_extensions/management/technical_response.py", line 40, in null_technical_500_response
    raise exc_value.with_traceback(tb)
  File "/home/sam/.pyenv/versions/3.11.2/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/.pyenv/versions/3.11.2/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/.pyenv/versions/3.11.2/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/.pyenv/versions/3.11.2/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/.pyenv/versions/3.11.2/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/.pyenv/versions/3.11.2/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sam/.pyenv/versions/3.11.2/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/sam/.pyenv/versions/3.11.2/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/.pyenv/versions/3.11.2/lib/python3.11/site-packages/drf_yasg/views.py", line 94, in get
    schema = generator.get_schema(request, self.public)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/.pyenv/versions/3.11.2/lib/python3.11/site-packages/drf_yasg/generators.py", line 276, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/.pyenv/versions/3.11.2/lib/python3.11/site-packages/drf_yasg/generators.py", line 482, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/.pyenv/versions/3.11.2/lib/python3.11/site-packages/drf_yasg/generators.py", line 524, in get_operation
    operation = view_inspector.get_operation(operation_keys)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/.pyenv/versions/3.11.2/lib/python3.11/site-packages/drf_yasg/inspectors/view.py", line 33, in get_operation
    query = self.get_query_parameters()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/.pyenv/versions/3.11.2/lib/python3.11/site-packages/drf_yasg/inspectors/view.py", line 293, in get_query_parameters
    natural_parameters = self.get_filter_parameters() + self.get_pagination_parameters()
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/.pyenv/versions/3.11.2/lib/python3.11/site-packages/drf_yasg/inspectors/base.py", line 428, in get_pagination_parameters
    return self.probe_inspectors(self.paginator_inspectors, 'get_paginator_parameters',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/.pyenv/versions/3.11.2/lib/python3.11/site-packages/drf_yasg/inspectors/base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/.pyenv/versions/3.11.2/lib/python3.11/site-packages/drf_yasg/inspectors/query.py", line 22, in get_paginator_parameters
    fields = paginator.get_schema_fields(self.view)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/.pyenv/versions/3.11.2/lib/python3.11/site-packages/rest_framework/pagination.py", line 313, in get_schema_fields
    assert coreapi is not None, 'coreapi must be installed to use `get_schema_fields()`'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: coreapi must be installed to use `get_schema_fields()`
```

## Your Environment

```code
Fedora Linux 38 (all packages up to date)
Python 3.11.4
poetry 1.5.1
pip 23.1.2
```

**Comment by onegreyonewhite** [comment]
@JordanRickman @skamansam @yamnikov-oleg install drf-yasg with 'coreapi' extra and it'll be installed with coreapi. Watch #856 (I dont know why it closed, because @JoelLefkowitz haven't release new version with #857 which totally remove coreapi requirement in default drf filter backends).

If release include #862 drf-yasg will respect drf schema for paginators too (without coreapi).

But if you still need coreapi you should install `drf-yasg[coreapi]` instead of `drf-yasg`.

**Comment by JoelLefkowitz** [comment]
Version 1.21.7 now released
https://pypi.org/project/drf-yasg/1.21.7
